version: "3"

services:
  api:
    build: ./services/gateway-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    container_name: gateway-api  
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: gateway-db